CREATE TABLE IF NOT EXISTS markets (
	market_name VARCHAR(100) PRIMARY KEY,
	keys_id SERIAL UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS markets_api_keys (
	key_id SERIAL PRIMARY KEY,
	api_key VARCHAR(64) UNIQUE NOT NULL,
	market_keys_id INT NOT NULL REFERENCES markets(keys_id) ON DELETE CASCADE
    is_active BOOLEAN NOT NULL
);