services:
    price-service:
        container_name: price-service

        build: .

        volumes:
          - price-service-volume:/logs

    by-pass-service:
        container_name: by-pass-service

        build: ./tools/repository/api/by_pass_service

        network_mode: container:price-service

        depends_on:
          - price-service

volumes:
    price-service-volume:
        name: logs
